# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- azure-pipelines11

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: yarn workspace @animes-united/server install --frozen-lockfile
  displayName: 'Installing @animes-united/server'

- script: yarn workspace @animes-united/server test
  displayName: 'Testing @animes-united/server'
  env:
    MONGODB_URI_TEST: $(MONGODB_URI_TEST)
    PUPPETEER_DEBUG: $(PUPPETEER_DEBUG)

- script: yarn workspace @animes-united/server build
  displayName: 'Building @animes-united/server'